---
title: "Vector and Function Spaces -- Summary"
listing:
  contents: "chapters"
  sort: "title asc"
  type: table
---

For every chapter of the lecture notes "Vector- and function spaces", this document lists the following items:

1. A brief summary

2. Not covered in class: sections which we have not or only briefly covered, and are not part of the exam (neither theory nor exercise). This corresponds to (subsections) that (should) have a ($\star$) indicator in the lecture notes.

3. Important concepts: these mostly correspond to definitions, sometimes the definition is hidden inside a proposition or theorem. You do not need to know the literal definition, but you should be able to understand and use this term or concept correctly, both for theory and exercise.

4. Important theorems and propositions: list of proofs that need to be known (actively) or understood (passively) for the theory exam

5. Additional topics for applications / exercises: what you need to know for the exercises, in particular if it is additional material that you do not need to know for theory
