---
title: "Chapter 1 --- Elementary algebraic structures"
author: "Jutho Haegeman"
date: "09/25/2023"
---

# Summary

This chapter lists the basic mathematical structures and terminology that we will need and use, and doing so, also specifies the convention and notations that we will use for those. This should be almost completely repition; there will be no direct theory questions about this, but you should of course be able to use and understand this terminology

# Not convered in class

Section 1.2.3 and 1.2.4 were only partially covered in class. We have only introduced group actions (and representations as special case), but not discussed the different properties it can have (faithful, free, transitive), nor the associated concepts of orbits and stabilizer subgroups. We have discussed the kernel of a group homomorphism and the special role of normal subgroups and quotient groups, but we have not at all discussed exact sequences.

# Important concepts

* Set, subset, intersection, union
* Map, domain, codomain, argument, image, injective, surjective, bijective
* Set cardinality: finite, countably infinite, uncountable $=$ uncountably infinite
* Equivalence relation (and partial order relation)
* Binary operation, associativity, commutativity, neutral element and inverses
* Group, subgroup
* Structure preserving map $=$ homomorphism, isomorphism, endomorphism, automorphism group
* kernel of a group homomorphism, normal subgroup
* Permutation, parity or signature of permutation
* Ring, field
* Vector space, linear combination, linear span, complete set, linear independence, basis, dimension, coordinates (coordinate isomorphism)
* Linear map, linear operator, linear transformation, general linear group
* Subspace, disjoint subspaces, direct sum, complement, codimension, quotient space,
* Algebra, commutator

# Lemmas, propositions and theorems

No proofs from Chapter 1

# For applications / exercises

Understanding the concepts and being able to recognise the relevant structures for exercises and examples
