---
title: "Chapter 8 --- Linear differential operators"
author: "Jutho Haegeman"
date: "12/05/2023"
---

# Summary

This chapter provides an in-depth study of differential operators, and their role in the study of linear differential equations with boundary conditions. We discuss how to construct the "formal adjoint" of a differential operator using partial integration, and how it relates to the boundary condition to actually construct the adjoint. We discuss how to decompose the solution of a differential equation in different parts, and how to study the existence and uniqueness of these different contributions. The adjoint plays a role via the Fredholm alternative theorem. Also, we discuss when a second order differential operator is self-adjoint (known as a Sturm-Liouville operator).

To better understand the role of boundary conditions, we take an extended detour via initial value problems, for which we can formally construct the solution (as a path ordered exponential), and we also discuss practical recipes (via a Taylor expansion or a generalisation thereof, known as Frobenius method). We find that we need $p$ boundary conditions for a $p$th order differential equation to be well balanced. Finally then, we can construct the solution to the inhomogeneous differential equation (with homogeneous boundary conditions) using the Green's function.

We then move on using differential operators in eigenvalue problems. The purpose thereof is for solving higher-dimensional partial differential equations, for which the spectral decomposion of a differential operator (if it exists) turns out to be very useful.

# Not covered in class

While all subsections were mentioned in the lectures, several were only briefly mentioned and do not contain material that needs to be known for the theory exam. In particular, no theory from subsections 8.2.5 - 8.2.8 need to be known, but for the exercises, you need to know how to use a Taylor series and more generally the method of Frobenius to construct solutions of second order differential equations. Also subsections 8.4.3 and 8.4.4 as well as section 8.5 were only briefly mentioned. 

# Important concepts

* Homogeneous and inhomogeneous (linear) differential equation, homogeneous and inhomogeneous boundary conditions, formal adjoint of a linear differential operator, Sturm-Liouville operator, separated boundary conditions.
* A $p$th order differential equation is well balanced (likely to have a solution that exists and is unique for any right hand side) if it has exactly $p$ boundary conditions; this is a necessary but not sufficient condition. Having $p$ boundary conditions is also necessary (but not sufficient) to be a self-adjoint operator.
* Uniqueness is associated with $\mathrm{ker}(\hat{L})$, existence with $\mathrm{ker}(\hat{L}^\dagger)$ (using Fredholm's alternative theorem).
* Initial value problem, fundamental matrix solution, propagator and time-ordered exponential, Wronskian, Floquet theorem
* Boundary value problem, Dirichlet and Neumann conditions for second order problems, Green's function, Green's operator as inverse of differential operator, adjoint of the Green's operator
* Sturm-Liouville eigenvalue problems: a regular Sturm-Liouville operator admits a spectral decompositoin where the eigenvectors provide a complete orthonormal basis for the Hilbert space, and can thus be used to compute e.g. the exponential or inverse (= Green's function) (Remark 8.31 and 8.32)


# Lemmas, propositions, theorems

Important active proofs:

* Proposition 8.3 and Corollary 8.4 (it is sufficient if you can prove this for the case $p=2$)
* Proposition 8.5 and Corollary 8.6
* Constructing the bilinear concomitant of the Sturm-Liouville operator (eq 8.30)
* Verifying that it is self-adjoint with respect to separated or periodic boundary conditions.
* Theorem 8.12
* Proposition 8.13
* Proposition 8.14
* Proposition 8.15
* Proposition 8.16
* Theorem 8.17

Important passive proofs:

* Proposition 8.9 and its generalisation to the inhomogeneous case, Proposition 8.18

No theorems beyond subsection 8.2.4; you need to understand examples and use the concepts (see above) in exercises.

# For applications / exercises

* Be able to apply the Frobenius method, in particular for second order problems (Remarks 8.25 and 8.26). This requires that you can recognize/identify a regular singular point, and that you can derive the indicial equation. Also applying the simpler version (a Taylor series ansatz) when there is no singular point (coefficient of highest derivative is nowhere zero).

* Understand how to use a Green's function, and how to construct it in the case of a second order problem with separated boundary conditions (p305 - 306, in particular eq 8.123).

* Solve (sufficiently simple) Sturm-Liouville problems and use the resulting spectral decomposition to compute the corresponding Green's function or to solve time-dependent problems (computing $\exp(t \hat{L})$)