---
title: "Chapter 4 --- Norms and distances"
author: "Jutho Haegeman"
date: "10/17/2023"
---

# Summary

This chapter introduces the concept of a norm, and then discusses at length how this can be used to make sense of limits of sequences of vectors, mostly in infinite-dimensional vector spaces, where there are some surprises and not everything is very intuitive. Then, we discuss the implications for linear maps on such normed vector spaces.

# Not covered in class

Section 4.4.1 was only discussed at high level. In section 4.4.2, I only mentioned the definition of the condition number. The contents of this section should be more or less equivalent to what is covered in Python 4 Scientists. If you are not following this course, it might be useful to read about the importance of the condition number.

Section 4.4.3 was not discussed at all. If you want some theoretical background about Markov chains and the Google PageRank algorithm, feel free to read ;-).

# Important concepts

* Norm, Hölder p-norm
* Metric ($=$ distance), distance in a normed vector space, isometric map, limit of a sequence, continuity of a map, open subset, closed subset, closure, dense subset
* Equivalence of norms
* Cauchy sequence, metric completeness (=every Cauchy sequence has limit), Banach space (=metric complete normed vector space), closed subspace, dense subspace, complete set, absolutely converging series, Schauder basis
* Norm for linear maps, Frobenius norm, bounded map $\equiv$ continuous map, subordinate norm, submultiplicative norm for operators, induced norm ($=$ operator norm), spectral radius
* Condition number

Finite-dimensional vector spaces: all norms are equivalent, always metric complete, finite-dimensional subspaces are always closed

Infinite-dimensional vector spaces: proper infinite-dimensional subspaces of a Banach space can be dense: there is no intuitive or visual way to interpret this concept, there are vectors which are not in this subspace, but nonetheless they are arbitrary close to it (measured using the norm of the surrounding vector space). 

Linear maps: continuous if and only if bounded, bounded linear maps with operator norm are metric complete, induced norm is subordinate and submultiplicative, Gelfand formula for spectral radius


# Lemmas, propositions, theorems

No proofs about compactness (Theorem 4.10, Lemma 4.11), metric completeness and Banach spaces (section 4.2 and also Proposition 4.19)

Active proofs:

- Hölder norms: inequalities of Young, Hölder and Minkowski (Lemma 4.1, lemma 4.2, proposition 4.3)
- Continuity of norm (proposition 4.5)
- Characterisation of norm equivalence (Proposition 4.7)
- Equivalence between boundedness and continuity of linear maps (Proposition 4.17)
- Boundedness of linear maps with finite-dimensional domain (Proposition 4.18)
- Submultiplicativity of operator norm (Proposition 4.20)
- Consistence of induced and Frobenius matrix norms (Proposition 4.21, 4.22)
- Relation between submultiplicative norms and spectral radius (Proposition 4.23, 4.24)

Passive proofs:

- Continuity of vector addition and scalar addition (proposition 4.6)
- equivalence of all norms in finite dimensional spaces (proposition 4.8)
- dual norm (proposition 4.25)

No theory from section 4.4

# For applications / exercises

* Computing norms
* Proving inequality relations between standard $p$ norms or computing induced norms for matrices.

  (But this chapter serves mostly theoretical purposes.)
